### ISSUE TITLE
Asides

### ISSUE THREAD

**Issue by pdworkman** [dhniceday/obsidian-sticky-notes#1]
Asides disappear. 

I copied the aside note in the readme file.

I have tried it in the sandbox vault and they disappear there too. 

I can see them in source mode, but they are invisible in live preview. 

> [!STICKY|aside left purple title]
> Sticky Note
> This one is put aside, purple with its first line bold

**Comment by dhniceday** [comment]
Can you please deactivate all other css snippets and use the default theme.
Please report if issue still persists.

**Comment by dhniceday** [comment]
The sticky notes are not developed for live preview (i never use that). They will work in Reading mode only.
