### ISSUE TITLE
Complicated in using it

### ISSUE THREAD

**Issue by muhirwa45** [dhniceday/obsidian-sticky-notes#2]
Could you gide me to install it in obsidian

**Comment by dhniceday** [comment]
Not installation is required as this is only a CSS snippet. How to use CSS snippets is explained in the Obsidian documentation. https://help.obsidian.md/Extending+Obsidian/CSS+snippets

Let me know in case you need help.

**Comment by muhirwa45** [comment]
I did. Thank you

**Comment by dhniceday** [comment]
Instructions given to user
